version: '3.8'

services:
  back-koks:
    build:
      context: ./back-koks
      dockerfile: Dockerfile
    ports:
      - "3004:3003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/MineCoke?schema=public
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: MineCoke
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MineCoke"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: