"""empty message

Revision ID: 9603b3e57af1
Revises: ede3ed9676dd
Create Date: 2026-03-02 11:38:38.050337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9603b3e57af1'
down_revision = 'ede3ed9676dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storyboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storyboards', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###
