"""empty message

Revision ID: cdf14bafc9b3
Revises: 
Create Date: 2026-02-27 17:47:30.197467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf14bafc9b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_filename', sa.String(length=256), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('camera_params',
    sa.Column('params_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vertical_fov', sa.Float(), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=False),
    sa.Column('resolution_height', sa.Integer(), nullable=False),
    sa.Column('is_dictionary', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('params_id')
    )
    op.create_table('local_weather',
    sa.Column('weather_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Float(), nullable=False),
    sa.Column('is_use_api', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_table('opt1_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taxons', sa.JSON(), nullable=True),
    sa.Column('total_flight_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('opt2_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('total_flight_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('opt_methods',
    sa.Column('method_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pretty_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('method_id')
    )
    op.create_table('storyboard_names',
    sa.Column('storyboard_name_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pretty_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('storyboard_name_id')
    )
    op.create_table('trajectories_shapes',
    sa.Column('shapes_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('points', sa.JSON(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('obstacles', sa.JSON(), nullable=True),
    sa.Column('points_count', sa.Integer(), nullable=False),
    sa.Column('obstacles_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shapes_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('drone_params',
    sa.Column('params_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('camera_params_id', sa.Integer(), nullable=True),
    sa.Column('base_distance', sa.Float(), nullable=True),
    sa.Column('planned_distance', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('battery_time', sa.Float(), nullable=True),
    sa.Column('hover_time', sa.Float(), nullable=True),
    sa.Column('wind_resistance', sa.Float(), nullable=True),
    sa.Column('is_consider_obstacles', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_params_id'], ['camera_params.params_id'], ),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('params_id')
    )
    op.create_table('storyboards',
    sa.Column('storyboard_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('total_flight_time', sa.Float(), nullable=True),
    sa.Column('count_frames', sa.Integer(), nullable=True),
    sa.Column('disk_space', sa.BigInteger(), nullable=True),
    sa.Column('step_x', sa.Float(), nullable=True),
    sa.Column('step_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['name_id'], ['storyboard_names.storyboard_name_id'], ),
    sa.PrimaryKeyConstraint('storyboard_id')
    )
    op.create_table('flight_schemas',
    sa.Column('schema_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('drone_params_id', sa.Integer(), nullable=True),
    sa.Column('traj_shapes_id', sa.Integer(), nullable=True),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('point_storyboard_id', sa.Integer(), nullable=True),
    sa.Column('recommend_storyboard_id', sa.Integer(), nullable=True),
    sa.Column('optimal_storyboard_id', sa.Integer(), nullable=True),
    sa.Column('priority_opt_method_id', sa.Integer(), nullable=True),
    sa.Column('opt1_result_id', sa.Integer(), nullable=True),
    sa.Column('opt2_result_id', sa.Integer(), nullable=True),
    sa.Column('schema_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drone_params_id'], ['drone_params.params_id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['base_images.image_id'], ),
    sa.ForeignKeyConstraint(['opt1_result_id'], ['opt1_results.result_id'], ),
    sa.ForeignKeyConstraint(['opt2_result_id'], ['opt2_results.result_id'], ),
    sa.ForeignKeyConstraint(['optimal_storyboard_id'], ['storyboards.storyboard_id'], ),
    sa.ForeignKeyConstraint(['point_storyboard_id'], ['storyboards.storyboard_id'], ),
    sa.ForeignKeyConstraint(['priority_opt_method_id'], ['opt_methods.method_id'], ),
    sa.ForeignKeyConstraint(['recommend_storyboard_id'], ['storyboards.storyboard_id'], ),
    sa.ForeignKeyConstraint(['traj_shapes_id'], ['trajectories_shapes.shapes_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['weather_id'], ['local_weather.weather_id'], ),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.drop_table('schemas')
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('resolution_width',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('resolution_height',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_wind_resistance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('max_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('min_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('battery_life',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment='Время работы батареи, сек')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.alter_column('battery_life',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment=None,
               existing_comment='Время работы батареи, сек')
        batch_op.alter_column('min_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('max_wind_resistance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('resolution_height',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('resolution_width',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('weight')

    op.create_table('schemas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('points_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('flight_time', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('is_weather_conditions', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('schemas_pkey'))
    )
    op.drop_table('flight_schemas')
    op.drop_table('storyboards')
    op.drop_table('drone_params')
    op.drop_table('users')
    op.drop_table('trajectories_shapes')
    op.drop_table('storyboard_names')
    op.drop_table('opt_methods')
    op.drop_table('opt2_results')
    op.drop_table('opt1_results')
    op.drop_table('local_weather')
    op.drop_table('camera_params')
    op.drop_table('base_images')
    # ### end Alembic commands ###
